// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwMSYYhpBeO8OOaCWHR-PLu-_WraJw9M',
    appId: '1:36060630529:web:9a3184e3176c5ae8ebfa00',
    messagingSenderId: '36060630529',
    projectId: 'utkarsh-8cf54',
    authDomain: 'utkarsh-8cf54.firebaseapp.com',
    storageBucket: 'utkarsh-8cf54.firebasestorage.app',
    measurementId: 'G-DJGTCRE5H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBEvoMX0pFOjgh_dUqJXR0Ghmt4af7fU',
    appId: '1:36060630529:android:7cd016722d5905d1ebfa00',
    messagingSenderId: '36060630529',
    projectId: 'utkarsh-8cf54',
    storageBucket: 'utkarsh-8cf54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQhUkxvoS6ChcfOgisMoaUi50P_yxsUzc',
    appId: '1:36060630529:ios:cc4db74ec0e95ebbebfa00',
    messagingSenderId: '36060630529',
    projectId: 'utkarsh-8cf54',
    storageBucket: 'utkarsh-8cf54.firebasestorage.app',
    androidClientId: '36060630529-aa54o3sfh6srpnuda0n7ohphh3qj6a3b.apps.googleusercontent.com',
    iosClientId: '36060630529-6g1sh30ue3um0va9gdgglspmbltk8il7.apps.googleusercontent.com',
    iosBundleId: 'com.example.utkarsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQhUkxvoS6ChcfOgisMoaUi50P_yxsUzc',
    appId: '1:36060630529:ios:cc4db74ec0e95ebbebfa00',
    messagingSenderId: '36060630529',
    projectId: 'utkarsh-8cf54',
    storageBucket: 'utkarsh-8cf54.firebasestorage.app',
    androidClientId: '36060630529-aa54o3sfh6srpnuda0n7ohphh3qj6a3b.apps.googleusercontent.com',
    iosClientId: '36060630529-6g1sh30ue3um0va9gdgglspmbltk8il7.apps.googleusercontent.com',
    iosBundleId: 'com.example.utkarsh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfwMSYYhpBeO8OOaCWHR-PLu-_WraJw9M',
    appId: '1:36060630529:web:31c35206603bac83ebfa00',
    messagingSenderId: '36060630529',
    projectId: 'utkarsh-8cf54',
    authDomain: 'utkarsh-8cf54.firebaseapp.com',
    storageBucket: 'utkarsh-8cf54.firebasestorage.app',
    measurementId: 'G-0GPN2XL53D',
  );
}
